# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-maxquant-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::libopenblas=0.3.3
  - conda-forge::python=3.9.2
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.8.1
  - r-hexbin=1.28.2
  - mono=5.14.0.177
  - bioconda::maxquant=1.6.10.43
  - bioconda::sdrf-pipelines=0.0.12
  - bioconda::bioconductor-normalyzerde=1.8.0