name: normalizerde

description: NormalyzerDE is a software designed to ease the process of selecting an optimal normalization approach for your dataset and to perform subsequent differential expression analysis.
keywords:
  - Peptide identification
  - Testing and assessment
  - Mathematical methods
tools:
  - normalizerde:
      description: Evaluation of normalization methods and calculation of differential expression analysis statistics
      homepage: http://quantitativeproteomics.org/normalyzerde
      documentation: http://quantitativeproteomics.org/normalyzerde
      tool_dev_url: https://github.com/ComputationalProteomics/NormalyzerDE
      doi: "https://doi.org/10.1021/acs.jproteome.8b00523"
      licence: ['Artistic-2.0']
params: 
  - outdir:
      type: string
      description: |
          The pipeline's output directory. By default, the module will
          output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
          Value for the Nextflow `publishDir` mode parameter.
          Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
          Run the module with Conda using the software specified
          via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
          Instead of directly downloading Singularity images for use with Singularity,
          force the workflow to pull and convert Docker containers instead.
input:
  - sdrf_file:
      type: path
      description: SDRF file for information regarding exp setup
      pattern: "*.{tsv}"
  - exp_file:
      type: path
      description: File containing information regarding exp
      pattern: "*.{tsv}"
  - protein_file:
      type: path
      description: proteins from maxquant
      pattern: "*.{txt}"
  - exp_file2:
      type: file
      description: File with information on exp setup.
      pattern: "*.{tsv}"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - norm_stat:
      type: file
      description: Results
      pattern: "*.{tsv}"
  - norm_meth:
      type: file
      description: Information on norm meth.
      pattern: "*.{txt}"

authors:
  - "@nicni16"
